### ISSUE TITLE
[ERROR] BlhostBase: Unsupported protocol version: P1.3.0

### ISSUE THREAD

**Issue by a-sapuppo** [Lauszus/pyblhost#6]
how to update ?

```
pyblhost serial ping -p /dev/ttyUSB0 -b 115200
[INFO] BlhostBase: Sending ping command
[INFO] BlhostBase: Ping response: version: P1.3.0, options: 0
[ERROR] BlhostBase: Unsupported protocol version: P1.3.0
[INFO] Ping responded in 1 attempt(s)
```

**Comment by Lauszus** [comment]
The latest version when I wrote this was P1.2.0.

Can you send me a link to the bootloader you are using?

Alternatively you can try to disable this check: https://github.com/Lauszus/pyblhost/blob/main/pyblhost/pyblhost.py#L542 and see if it works.

**Comment by Lauszus** [comment]
You need to compare the protocol for 1.2.0 and 1.3.0 and see what has changed. It might be backwards compatible.

**Comment by Lauszus** [comment]
I can't find any information on what has changed between the two protocol. I'll just assume that it's backward compatible.

**Comment by Lauszus** [comment]
Thanks for reporting the issue. It has now been fixed. I'll make a new release shortly :)

**Comment by Lauszus** [comment]
I've now made a new release.
